# run: conda env create --file environment.yml
name: wss_tem
channels:
  - defaults
dependencies:
- python=3.8.18
- pip=23.3.1
- ipython=8.12.2
- tensorboard=2.12.1
- yaml=0.2.5
- matplotlib=3.7.2
- jupyter=1.0.0
- notebook=7.0.6
- numpy=1.24.3
- pillow=10.0.1
- pip:
  - torch==2.1.2
  - torchsearchsorted=1.1
  - tqdm==4.66.1
  - nbformat==5.7.0
  - nvidia-cublas-cu12==12.1.3.1
  - nvidia-cuda-cupti-cu12==12.1.105
  - nvidia-cuda-nvrtc-cu12==12.1.105
  - nvidia-cuda-runtime-cu12==12.1.105
  - nvidia-cudnn-cu12==8.9.2.26
  - nvidia-cufft-cu12==11.0.2.54
  - nvidia-curand-cu12==10.3.2.106
  - nvidia-cusolver-cu12==11.4.5.107
  - nvidia-cusparse-cu12==12.1.0.106
  - nvidia-nccl-cu12==2.18.1
  - nvidia-nvjitlink-cu12==12.3.101
  - nvidia-nvtx-cu12==12.1.105